# Generated by Django 4.1.4 on 2023-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_empdet_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
